name: vc2024
channels:
  - pytorch
  - plotly
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - absl-py=1.4.0
  - accelerate=0.27.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - anyio=4.3.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.13
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.5
  - aws-c-mqtt=0.10.2
  - aws-c-s3=0.5.2
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.2
  - aws-sdk-cpp=1.11.267
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - blas=2.121
  - blas-devel=3.9.0
  - bleach=6.1.0
  - blinker=1.6.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.2
  - cairo=1.18.0
  - catalogue=2.0.10
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - comm=0.2.1
  - confection=0.1.4
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cuda-cccl=12.3.101
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-opencl-dev=12.3.101
  - cuda-profiler-api=12.3.101
  - cuda-runtime=12.1.0
  - cycler=0.12.1
  - cymem=2.0.8
  - cython-blis=0.7.10
  - datasets=2.14.4
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diffusers=0.26.3
  - dill=0.3.7
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.4.1
  - fsspec=2024.2.0
  - getopt-win32=0.1
  - gettext=0.21.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.1
  - graphite2=1.3.13
  - graphviz=9.0.0
  - grpcio=1.61.1
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=8.3.0
  - hpack=4.0.0
  - httpcore=1.0.4
  - httpx=0.27.0
  - huggingface_hub=0.20.2
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - intel-openmp=2024.0.0
  - ipykernel=6.29.2
  - ipympl=0.9.3
  - ipython=8.22.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.2
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - json5=0.9.17
  - jsonpointer=2.4
  - jsonschema=4.21.1
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.21.1
  - jupyter-lsp=2.2.2
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.5
  - jupyter_server_terminals=0.5.2
  - jupyterlab=4.1.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.3
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - langcodes=3.3.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.1
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.4.107
  - libcurand-dev=10.3.4.107
  - libcurl=8.5.0
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.19
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libglib=2.78.4
  - libgoogle-cloud=2.21.0
  - libgoogle-cloud-storage=2.21.0
  - libgrpc=1.61.1
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libogg=1.3.4
  - libparquet=15.0.0
  - libpng=1.6.42
  - libprotobuf=4.25.2
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuv=1.47.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.4.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.8.3
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mistune=3.0.2
  - mkl=2024.0.0
  - mkl-devel=2024.0.0
  - mkl-include=2024.0.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.5
  - multiprocess=0.70.15
  - munkres=1.1.4
  - murmurhash=1.0.10
  - nbclient=0.8.0
  - nbconvert-core=7.16.1
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.1.0
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.2.1
  - orc=1.9.2
  - overrides=7.7.0
  - packaging=23.2
  - pandas=2.2.1
  - pandocfilters=1.5.0
  - pango=1.50.14
  - parso=0.8.3
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.0
  - plotly=5.19.0
  - ply=3.11
  - preshed=3.0.9
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.42
  - protobuf=4.25.2
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyarrow=15.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydantic=2.6.3
  - pydantic-core=2.16.3
  - pygments=2.17.2
  - pyjwt=2.4.0
  - pyopenssl=24.0.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-graphviz=0.20.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.12
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=306
  - pywinpty=2.0.12
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - re2=2023.09.01
  - referencing=0.33.0
  - regex=2023.12.25
  - requests=2.31.0
  - requests-oauthlib=1.3.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.18.0
  - rsa=4.7.2
  - safetensors=0.4.2
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - send2trash=1.8.2
  - setuptools=69.1.1
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - smart_open=6.4.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.4.8
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.11.0
  - tenacity=8.2.2
  - tensorboard=2.6.0
  - tensorboard-plugin-wit=1.6.0
  - terminado=0.18.0
  - thinc=8.2.2
  - threadpoolctl=3.3.0
  - timm=0.9.16
  - tinycss2=1.2.1
  - tk=8.6.13
  - tokenizers=0.15.2
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.1
  - transformers=4.38.1
  - typer=0.9.0
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.2.1
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wasabi=0.10.1
  - wcwidth=0.2.13
  - weasel=0.3.4
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - werkzeug=2.3.8
  - wheel=0.42.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.17
  - xorg-libxt=1.3.0
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - en-core-web-sm==3.7.1
      - torchaudio==2.2.1
      - torchvision==0.17.1
